### ISSUE TITLE
Understanding Orky

### ISSUE THREAD

**Issue by jwhiteacre** [MattSFT/Orky#5]
Am I correct that Orky is a bot running at this URL https://scriptorbot.azurewebsites.net.  I can then have my Orky bot connect to it to receive commands.  And I can add the Orky application to my MS Teams.  

This means all my commands and responses flow through Orky at https://scriptorbot.azurewebsites.net and can recorded there.

**Comment by MatSFT** [comment]
Yes it does. That's one of the reasons why it isn't exactly production ready. The instance at https://scriptorbot.azurewebsites.net/ is my own instance actually but all the code for it is in the Orky folder so you could deploy your own instance and have your hubots connect to your own instance of Orky.

**Comment by MatSFT** [comment]
If you are just running one hubot instance than Orky might be overkill as a solution, it really becomes much more useful when you have multiple hubots to manage and you don't want to expose all of them publicly and register them on BotFramework.

I'm gonna go ahead and close this issue. Let me know if you need help with anything else.
